#ifndef GL_OBJECT_TYPE_H
# define GL_OBJECT_TYPE_H

typedef enum e_object_type
{
	GL_TYPE_LINE,
	GL_TYPE_RECT,
	GL_TYPE_CUBE,
	GL_TYPE_CONE,
	GL_TYPE_CYLINDER,
	GL_TYPE_WIRE_RECT,
	GL_TYPE_WIRE_CUBE,
	GL_TYPE_WIRE_CONE,
	GL_TYPE_WIRE_CYLINDER,
	GL_TYPE_GROUP,
	GL_TYPE_2D_LINE,
	GL_TYPE_2D_RECT,
	GL_TYPE_2D_WIRE_RECT,
	GL_TYPE_COUNT
}	t_object_type;

#endif
